spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: fs1lm3gl5tt
    #driver-class-name: com.mysql.cj.jdbc.Driver