spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null  #driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: 5f88f757-47b8-4347-8ef7-2013407a23ef
  expiration: 999999