spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: fs1lm3gl5tt
  jackson:
    default-property-inclusion: non_null  #driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: 5f88f757-47b8-4347-8ef7-2013407a23ef
  expiration: 999999